### ISSUE TITLE
Does not work nicely with custom build script names

### ISSUE THREAD

**Issue by leonschreuder** [meonlol/gradle-tab-completion#5]
The completion works fine if your root build script is either named build.gradle or its name is set via rootProject.buildFileName = '...' or rootProject.buildFileName = "..." (actually also rootProject.buildFileName = "...' and rootProject.buildFileName = '...", but those will not compile anyway) exactly like that.
You cannot use a variable for the name, you cannot leave out the spaces around the equals sign or add more, it has to be at the start of a line without any preceding whitespaces, and you cannot use other constructs to set the name that are perfectly legal. In my case I do it for all projects like this which of course also does not work:

def setBuildFileNameRecursively
setBuildFileNameRecursively = { it ->
   it.buildFileName = "${it.name}.gradle"
   it.children.each { setBuildFileNameRecursively it }
}
setBuildFileNameRecursively rootProject
It would be nice if the completion would not require some narrow range of modification options but simply work. Is it really necessary to determine the root project filename upfront? Can't you use -p instead of -b for the call and use the project dir as cache key instead of the build file?

@Vampire I've copied your Issue for my script if you don't mind. I want to make sure this is not a problem for mine as well.

**Comment by Vampire** [comment]
I don't. :-)

**Comment by leonschreuder** [comment]
@Vampire Thanks 😊. I might have misunderstood your original question though. I thought it was about the cache not including other `*.gradle` files, but is seems it is about completing properties from files other than `settings.gradle`. Since I left out the property-completion entirely for the sake of simplicity, that is not a problem for my script. However, the problem I thought you where adressing is now fixed 😅.

**Comment by Vampire** [comment]
@meonlol no, this is not about properties, but about completion per-se, I think you still did not understand at all.

The script I reported against requires that the file name of the build script of your root project is either `build.gradle`, or set in `settings.gradle` with the exact character sequence `rootProject.buildFileName = '...'` or `rootProject.buildFileName = "..."`, including spaces. Many other legal ways to set the name, e. g. the recursive approach I mentioned make the completion not work at all, as the root build script file cannot be found which is used as cache key and for ruining Gradle with `-b`.

**Comment by leonschreuder** [comment]
@Vampire Ah, I see. Now I understand what you doing and and why this would break the script.
I've never deviated from the default `buildFileName` it so that explains my confusion.
Since my script doesn't read the variable at all, it's not a problem for me 😅.

Thanks for the feedback; it taught me something 😊.

**Comment by Vampire** [comment]
Well, from a very short look I think you have other problems, like considering only `*.gradle` __and__  considering all `*.gradle` for the cache, only supporting completion properly if at the root project directory and while you have to be at the root project directory, only the files in the current dir and down are considered for cache, while subprojects are not necessarily in sub-directories, .......

**Comment by leonschreuder** [comment]
You are correct about not being able to call it from sub-projects, but since most people run the gradle-wrapper from the root anyway, I felt this would cover most of the standard use-cases.
I'll be installing it at work this week, so we'll see how it holds up under pressure.

**Comment by Vampire** [comment]
Most people that you know maybe, I know enough people that don't do it. And besides that, if you e. g. have a structure like

- master (root project)
- subproject 1
- subproject 2

which is also quite common, this is also not supported properly.

Or when using `-b` or `-p` switch, besides calling Gradle from a subproject or even subdirectory. 

And if you name your files differently than `.gradle`, you also have a problem. You could e. g. run `gradlew -i help` and parse the output. It tells you exactly which files are evaluated, at least for the projects directly. Additionally you would need to consider all files recursively that are used with `apply from: '...'` and in any way of course all content of the buildSrc directory of course.
